Implement undo
hexatomic/hexatomic pull request #212
Opened 2020-08-12 20:12 UTC by thomaskrause

## Pull request type

 

N/A

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

N/A

## Other information

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added **or** the PR is neither a bug fix nor a feature
- [ ] Docs have been reviewed and added / updated if needed **or** the PR is neither a bug fix nor a feature
- [ ] The *Unreleased* section in CHANGELOG.md has been amended to reflect the changes in this PR if needed
- [ ] Build (`mvn verify`) was run locally and any changes were pushed
- [ ] The pull request is against the correct branch (`master` for bug fixes, `develop` for new functionality)
- [ ] [Dependencies and citation templates](https://github.com/hexatomic/hexatomic/tree/develop/releng/templates) have been updated where necessary **or** there are no new dependencies

---

# Checklist for maintainers

## Releases

- Do **NOT** push the green merge button on GitHub.  
Follow the latest version of the [developer/maintainer docs](https://hexatomic.github.io/hexatomic/dev/) for making releases.
- Check that license and citation information for dependencies are complete (each dependency has a folder in `/THIRD-PARTY/`).

2020-09-04 15:27 UTC, sdruskat requested changes
Thanks! Looking forward to seeing this in the product!

Albeit, the undo/redo buttons don't seem to update nicely, you always have to activate another view (or rather, the project manager view) for the buttons to change. I'm afraid that this doesn't work well for the user, so should be changed.

1. Open corpus
2. Open doc in graph editor
3. Do something
4. `Undo` doesn't visually update, although change is made
5. Click in Project Manager
6. `Undo` updates.
7. etc ...

![button-behaviour](https://user-images.githubusercontent.com/3007126/92256110-9398db80-eed3-11ea-8372-845647cb0a82.gif)

![ctrl-behaviour](https://user-images.githubusercontent.com/3007126/92256112-94317200-eed3-11ea-86be-9f6ac38ddf9e.gif)

2020-09-05 11:18 UTC, thomaskrause commented
Fix the issue with the non-enabled toolbar buttons by sending the necessary event (see 13.5 in https://www.vogella.com/tutorials/EclipseRCP/article.html) manually in the `ProjectManager`.

2020-09-10 14:18 UTC, sdruskat requested changes
Sorry for the delay in reviewing this.

Unfortunately I've stumbled over another bug, not sure if it was introduced in this PR, but should probably be fixed in this one: Saving throws an error.

1. Create new doc via "Add" buttons
2. Open in Grid Editor
3. Tokenize something
4. Save as project somewhere
5. Do another tokenization.
6a. Sometimes it works and new tokens are added
6b. Sometimes it doesn't, and then :boom: `InvocationTargetException` on Save

![bug](https://user-images.githubusercontent.com/3007126/92743808-2aa4de00-f381-11ea-9bc4-ac33d85b8ddd.gif)

```
16:16:06.701 [main] INFO  o.c.h.c.ApplicationLifecycle -
                Logging configured from internal configuration
16:16:06.732 [main] DEBUG o.c.h.c.ProjectManager -
                Starting Project Manager
16:16:19.625 [main] DEBUG o.c.h.c.ProjectManager -
                Adding 3 changes as checkpoint to undo list
16:16:20.016 [main] DEBUG o.c.h.c.ProjectManager -
                Adding 4 changes as checkpoint to undo list
16:16:20.370 [main] DEBUG o.c.h.c.ProjectManager -
                Adding 10 changes as checkpoint to undo list
16:16:20.371 [main] DEBUG o.c.h.c.CorpusStructureView -
                Selecting created document
16:16:24.872 [main] DEBUG o.c.h.c.ProjectManager -
                Adding 41 changes as checkpoint to undo list
16:16:24.873 [main] DEBUG o.c.h.g.GraphEditor -
                Received ANNOTATION_CHANGED event for changeset org.corpus_tools.hexatomic.core.undo.ChangeSet@1eca3ea7
16:16:42.155 [main] DEBUG o.c.h.c.ProjectManager -
                Adding 31 changes as checkpoint to undo list
16:16:42.156 [main] DEBUG o.c.h.g.GraphEditor -
                Received ANNOTATION_CHANGED event for changeset org.corpus_tools.hexatomic.core.undo.ChangeSet@3a3f96ab
16:16:51.830 [main] ERROR o.c.h.c.ProjectManager -
                Exception occured: Could not save project
java.lang.reflect.InvocationTargetException: null
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:397) ~[na:na]
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:469) ~[na:na]
	at org.corpus_tools.hexatomic.core.ProjectManager.saveTo(ProjectManager.java:405) ~[na:na]
	at org.corpus_tools.hexatomic.core.ProjectManager.save(ProjectManager.java:473) ~[na:na]
	at org.corpus_tools.hexatomic.core.handlers.SaveHandler.execute(SaveHandler.java:46) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58) ~[na:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318) ~[na:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252) ~[na:na]
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173) ~[na:na]
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156) ~[na:na]
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488) ~[na:na]
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487) ~[na:na]
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213) ~[na:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438) ~[na:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449) ~[na:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475) ~[na:na]
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89) ~[na:na]
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5687) ~[na:na]
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423) ~[na:na]
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4955) ~[na:na]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4448) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160) ~[na:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:166) ~[na:na]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657) ~[org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar:na]
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594) ~[org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar:na]
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447) ~[org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar:na]
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420) ~[org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar:na]
Caused by: java.lang.NullPointerException: null
	at org.corpus_tools.salt.util.internal.persistence.SaltXML10Writer.writeRelation(SaltXML10Writer.java:646) ~[na:na]
	at org.corpus_tools.salt.util.internal.persistence.SaltXML10Writer.writeDocumentGraph(SaltXML10Writer.java:422) ~[na:na]
	at org.corpus_tools.salt.util.internal.persistence.SaltXML10Writer.writeDocumentGraph(SaltXML10Writer.java:343) ~[na:na]
	at org.corpus_tools.salt.util.SaltUtil.saveDocumentGraph(SaltUtil.java:609) ~[na:na]
	at org.corpus_tools.salt.common.impl.SDocumentImpl.saveDocumentGraph(SDocumentImpl.java:189) ~[na:na]
	at org.corpus_tools.hexatomic.core.ProjectManager$1.run(ProjectManager.java:343) ~[na:na]
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122) ~[na:na]
```

2020-09-10 14:18 UTC, sdruskat commented on bundles/org.corpus_tools.hexatomic.core/Application.e4xmi
> +      <children xsi:type="menu:Menu" xmi:id="_ufSukMsLEemUdItNeSusZw" elementId="org.corpus_tools.hexatomic.core.menu.file" label="File" mnemonics="f">
```suggestion
      <children xsi:type="menu:Menu" xmi:id="_ufSukMsLEemUdItNeSusZw" elementId="org.corpus_tools.hexatomic.core.menu.file" label="&amp;File">
```

Fix mnemonics to work. I don't know if you have tried this at all, but the mnemonics field doesn't do anything AFAIK. <kbd>Alt</kbd> + <kbd>f</kbd> work only when adding an `&amp;` before the actual mnemonic in the menu label. Perhaps this is different on you system though?

2020-09-10 14:18 UTC, sdruskat commented on bundles/org.corpus_tools.hexatomic.core/Application.e4xmi
> +      <children xsi:type="menu:Menu" xmi:id="_c2kBYJ6CEeqcNd4BgS8ZlA" elementId="org.corpus_tools.hexatomic.core.menu.edit" label="Edit" mnemonics="e">
```suggestion
      <children xsi:type="menu:Menu" xmi:id="_c2kBYJ6CEeqcNd4BgS8ZlA" elementId="org.corpus_tools.hexatomic.core.menu.edit" label="&amp;Edit">
```

Same as above, mnemonics only work the old school SWT way.

2020-09-12 09:25 UTC, thomaskrause commented
> Unfortunately I've stumbled over another bug, not sure if it was introduced in this PR, but should probably be fixed in this one: Saving throws an error.

I checked and this bug is present in the current master branch (#220) and I would propose to fix this as a hotfix release (which should of course include a regression test). It might be related to #214 but this will only be clear after we find the root cause of this issue, which is obviously not the changes added in this PR.

2020-09-16 12:16 UTC, thomaskrause commented
> Unfortunately I've stumbled over another bug, not sure if it was introduced in this PR, but should probably be fixed in this one: Saving throws an error.

This is now fixed in `master` and integrated into this PR

2020-09-24 12:52 UTC, sdruskat commented on bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/undo/ChangeSet.java
> +  public ChangeSet(Collection<ReversibleOperation> changes) {
Wondering why Checkstyle hasn't complained about missing JavaDoc here ...

2020-09-24 12:54 UTC, sdruskat commented on bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/undo/operations/AddCorpusGraphOperation.java
> +   * Create a undo operation for adding a corpus graph to a Salt project.
```suggestion
   * A reversible operation for adding a corpus graph to a Salt project.
```

2020-09-24 12:56 UTC, sdruskat commented on bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/undo/operations/AddLayerToGraphOperation.java
> +   * Create a undo operation for a layer that was added to a graph.
```suggestion
   * A reversible operation for a layer that was added to a graph.
```

Using the verb IMHO is imprecise. Here and in the other classes implementing ReversibleOperation.

2020-09-24 12:56 UTC, sdruskat commented on bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/undo/operations/AddNodeToGraphOperation.java
> +   * Create a undo operation for a node that was added to a graph.
```suggestion
   * A reversible operation for a node that was added to a graph.
```

2020-09-24 12:56 UTC, sdruskat commented on bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/undo/operations/AddNodeToLayerOperation.java
> +   * Create a reversible operation for adding a node to a layer.
```suggestion
   * A reversible operation for adding a node to a layer.
```

2020-09-24 12:56 UTC, sdruskat commented on bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/undo/operations/AddRelationToGraphOperation.java
> +   * Create a undo operation for a relation that was added to a graph.
```suggestion
   * A reversible operation for a relation that was added to a graph.
```

2020-09-24 12:57 UTC, sdruskat commented on bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/undo/operations/LabelAddOperation.java
> +  public LabelAddOperation(LabelableElement container, String qname) {
Again, weird why Checkstyle didn't complain about missing Javadoc ...

2020-09-24 14:42 UTC, sdruskat commented on docs/dev/src/development/add-new-editor.md
> +A user interaction that manipulates the document graph can consist of multiple Salt API calls and you must mark the end of a user interaction by calling the `addCheckpoint()` function of the injected
```suggestion
A user interaction that manipulates the document graph can consist of multiple Salt API calls, each one of which may potentially lead to inconsistent states. You must therefore mark the end of a user interaction by calling the `addCheckpoint()` function of an injected `ProjectManager` instance.
```

I think this change suggestion better explains why you actually need to add checkpoints, but feel free to edit.

2020-09-24 14:46 UTC, sdruskat commented on docs/dev/src/development/automated-tests/README.md
>  You can also generate a test code coverage report by executing `mvn verify site -Pcoverage`.
```suggestion
```

Remove duplicated paragraph

2020-09-24 14:49 UTC, sdruskat commented on docs/dev/src/development/data-model/README.md
> +It also has a helper function to test if a given document is affected by its changes.
```suggestion
It also has a helper function to test if a given document is affected by its changes.

```

Add blank line for readability.

2020-09-24 14:52 UTC, sdruskat commented on pom.xml
> +								<organizationName>Stephan Druskat, Thomas Krause</organizationName>
I've tried to fix the respective bit in the POM configuration for the license plugin, but this keeps coming back :angry:.

2020-09-24 14:54 UTC, sdruskat commented on tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestCorpusStructure.java
> +  void testUndoRedo() {
```suggestion
  void testUndo() {
```

Doesn't test redos.

2020-09-24 14:57 UTC, sdruskat approved these changes
Approved with very few minor change suggestions.

How about that :tada:!

2020-09-24 16:43 UTC, thomaskrause commented on bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/undo/ChangeSet.java
> +  public ChangeSet(Collection<ReversibleOperation> changes) {
For simple constructors that just initialize a value with one argument seem to be handled like getter/setter functions which also don't need a JavaDoc.

2020-09-24 16:44 UTC, thomaskrause commented on bundles/org.corpus_tools.hexatomic.core/src/main/java/org/corpus_tools/hexatomic/core/undo/operations/LabelAddOperation.java
> +  public LabelAddOperation(LabelableElement container, String qname) {
See explanation above

2020-09-24 17:04 UTC, merged