Refactor grid editor data access
hexatomic/hexatomic pull request #218
Opened 2020-08-20 11:28 UTC by sdruskat

## Pull request type

 

- Refactoring (no functional changes, no API changes)

## What is the current behavior?

Data access from any given code point is hard, even given a `NatTable` object, as this is actively discouraged by the framework.

## What is the new behavior?

This PR refactors the grid editor so that calls to `NatTable.getDataValueByPosition(columnPosition, rowPosition)` returns the Salt object instead of just the value string.

## Does this introduce a breaking change?

No.

## Other information

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added **or** the PR is neither a bug fix nor a feature
- [ ] Docs have been reviewed and added / updated if needed **or** the PR is neither a bug fix nor a feature
- [ ] The *Unreleased* section in CHANGELOG.md has been amended to reflect the changes in this PR if needed
- [ ] Build (`mvn verify`) was run locally and any changes were pushed
- [ ] The pull request is against the correct branch (`master` for bug fixes, `develop` for new functionality)
- [ ] [Dependencies and citation templates](https://github.com/hexatomic/hexatomic/tree/develop/releng/templates) have been updated where necessary **or** there are no new dependencies

---

# Checklist for maintainers

## Releases

- Do **NOT** push the green merge button on GitHub.  
Follow the latest version of the [developer/maintainer docs](https://hexatomic.github.io/hexatomic/dev/) for making releases.
- Check that license and citation information for dependencies are complete (each dependency has a folder in `/THIRD-PARTY/`).

2020-09-14 12:38 UTC, thomaskrause requested changes
Seems good to me in general but I would really like to remove the "internal" package from the exported packages of the bundle (seem comment).

Also, I have trouble to add new events for only a selected range of token. E.g. for the GUM corpus, In the current master branch, empty cells are rendered for each token and I can add an event for any number of tokens.
![Peek 2020-09-14 14-44](https://user-images.githubusercontent.com/2168104/93087456-deb3ab00-f698-11ea-9a9b-d90e921e679d.gif).
But in this PR, I can only select the whole empty range between other annotations.
![Peek 2020-09-14 14-46](https://user-images.githubusercontent.com/2168104/93087608-17ec1b00-f699-11ea-88c5-f5b68ce48771.gif)

2020-09-14 12:38 UTC, thomaskrause commented on tests/org.corpus_tools.hexatomic.grid.tests/src/main/java/org/corpus_tools/hexatomic/grid/internal/style/TestSelectionStyleConfiguration.java
> +import org.corpus_tools.hexatomic.grid.internal.style.SelectionStyleConfiguration;
This import is not really used.
```suggestion
```

2020-09-14 12:38 UTC, thomaskrause commented on tests/org.corpus_tools.hexatomic.grid.tests/src/main/java/org/corpus_tools/hexatomic/grid/internal/bindings/TestFreezeGridBindings.java
> +    // UiBindingRegistry registry = mock(UiBindingRegistry.class);
Commented-out code line is not really informative
```suggestion
```

2020-09-15 19:15 UTC, sdruskat commented on bundles/org.corpus_tools.hexatomic.grid/META-INF/MANIFEST.MF
> +Export-Package: org.corpus_tools.hexatomic.grid.internal.style;x-internal:=true
I agree.

2020-09-15 19:27 UTC, sdruskat commented on bundles/org.corpus_tools.hexatomic.grid/META-INF/MANIFEST.MF
> +Export-Package: org.corpus_tools.hexatomic.grid.internal.style;x-internal:=true
Fixed in aac461420fae6fc9405b765fb25b78206212d284.

2020-09-15 19:35 UTC, sdruskat commented on bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/GridEditor.java
> +          if (((STextualDS) selection.getFirstElement()).getInRelations().isEmpty()) {
Makes sense.

2020-09-15 20:07 UTC, sdruskat commented on bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/GridEditor.java
> +          if (((STextualDS) selection.getFirstElement()).getInRelations().isEmpty()) {
Fixed in 3c80fbd3.

2020-09-15 20:36 UTC, sdruskat commented
Merged cell issue reported is fixed in https://github.com/hexatomic/hexatomic/pull/218/commits/00350b2aad9a38a7d04beea80d690168ce4897b3.

2020-09-17 08:33 UTC, thomaskrause approved these changes

2020-09-17 10:01 UTC, merged