Change annotation name for single cells
hexatomic/hexatomic pull request #231
Opened 2020-10-27 22:07 UTC by sdruskat

## Pull request type

 

Feature

## What is the current behavior?

Issue Number: fixes #228 

Currently, annotation names can only be changed for whole columns, not for single cells.

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

No.

## Other information

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added **or** the PR is neither a bug fix nor a feature
- [ ] Docs have been reviewed and added / updated if needed **or** the PR is neither a bug fix nor a feature
- [ ] The *Unreleased* section in CHANGELOG.md has been amended to reflect the changes in this PR if needed
- [ ] Build (`mvn verify`) was run locally and any changes were pushed
- [ ] The pull request is against the correct branch (`master` for bug fixes, `develop` for new functionality)
- [ ] [Dependencies and citation templates](https://github.com/hexatomic/hexatomic/tree/develop/releng/templates) have been updated where necessary **or** there are no new dependencies

---

# Checklist for maintainers

## Releases

- Do **NOT** push the green merge button on GitHub.  
Follow the latest version of the [developer/maintainer docs](https://hexatomic.github.io/hexatomic/dev/) for making releases.
- Check that license and citation information for dependencies are complete (each dependency has a folder in `/THIRD-PARTY/`).

2020-11-20 10:53 UTC, thomaskrause commented
While reviewing the PR, I found a NullPointerException when 

1. Opening the Salt `example-corpus` from our test project
2. Right-Clicking on the second annotation value of the Inf-Struct column and changing the name to "Inf-Struct2" (without a namespace).

The Stack trace is unfortunately very empty.

![npe-hexatomic-pr231](https://user-images.githubusercontent.com/2168104/99792194-086cd080-2b27-11eb-9669-ff6b279f63ad.gif)

2020-11-20 11:41 UTC, sdruskat commented
> While reviewing the PR, I found a NullPointerException when

Fixed (and fix tested) in https://github.com/hexatomic/hexatomic/pull/231/commits/da107ac04fa4d5d0e2e66930c2a37cb321237f1a.

2020-11-23 11:24 UTC, thomaskrause requested changes
In principal good to go, but we should change the error handling when an annotation with the same name already exist on the target node with a more user-friendly error message and make sure the state (including the synchronization between the Salt data model and the displayed grid) does not become invalid when this occurs.

2020-11-23 11:24 UTC, thomaskrause commented on bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/internal/data/GraphDataProvider.java
> +        node.createAnnotation(namespace, name, annotationValue);
This code removes the label from the old node, but does not handle if there is an existing annotation with the same name on the new node. It will simply throw an exception.
E.g. in the Salt example corpus, you could rename one of the `lemma` cells to `pos`

![hexatomic-pr231-existing-anno](https://user-images.githubusercontent.com/2168104/99955635-0011d100-2d85-11eb-98c6-9af4657f06e9.gif)

The following exception seems to leave Hexatomic in a problematic state, since I at least can't click on anything anywhere after acknowledging the exception. We really should handle this case explicitly here with a user-friendly message.

2020-11-23 14:36 UTC, sdruskat commented on docs/user/src/usage/grid-editor/editing-names.md
> +You can change annotation names either for all cells in one column, or only for selected cells frmo one or more columns.
```suggestion
You can change annotation names either for all cells in one column, or only for selected cells from one or more columns.
```

Typo yes, but the wrong fix ;).

2020-11-23 14:37 UTC, sdruskat commented on bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/internal/GridHelper.java
> +  private static String createWrongTypeMessage(String object, Class<?> expectedClass) {
Sure, I can do that. Would be nicer.

2020-11-23 14:38 UTC, sdruskat commented on bundles/org.corpus_tools.hexatomic.grid/src/main/java/org/corpus_tools/hexatomic/grid/internal/data/GraphDataProvider.java
> +        node.createAnnotation(namespace, name, annotationValue);
Oops, missed that case, thanks for catching it. Will recator to catch this in a user-friendly way.

2020-11-23 14:38 UTC, thomaskrause commented on docs/user/src/usage/grid-editor/editing-names.md
> +You can change annotation names either for all cells in one column, or only for selected cells frmo one or more columns.
Wow, that's a nice double typo. I remember that I had both variants and ruled out the wrong one, but obviously still wrote down the wrong version.

2020-11-27 11:05 UTC, thomaskrause approved these changes
Thanks for the update, the changes looks great to me now.

2020-11-27 11:06 UTC, merged

2020-11-27 15:53 UTC, sdruskat commented
🎉