Feature/update functionality
hexatomic/hexatomic pull request #267
Opened 2021-03-03 14:05 UTC by clachenmaier

## Pull request type
- Feature

## What is the current behavior?

Issue Number: https://github.com/hexatomic/hexatomic/issues/262

## What is the new behavior?

- Users can check via click on a menu item (e.g., *Help* > *Update*) whether new versions of Hexatomic (i.e., all installed features) are available, and can then choose to update the running installation.
- *Advanced:* Hexatomic checks at startup, whether updates are available, and notifies the user of this.
    - Users are able to switch off automatic update checks as well as notifications
    - 
## Does this introduce a breaking change?

N/A

## Other information

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added **or** the PR is neither a bug fix nor a feature
- [ ] Docs have been reviewed and added / updated if needed **or** the PR is neither a bug fix nor a feature
- [ ] The *Unreleased* section in CHANGELOG.md has been amended to reflect the changes in this PR if needed
- [ ] Build (`mvn verify`) was run locally and any changes were pushed
- [X] The pull request is against the correct branch (`master` for bug fixes, `develop` for new functionality)
- [ ] [Dependencies and citation templates](https://github.com/hexatomic/hexatomic/tree/develop/releng/templates) have been updated where necessary **or** there are no new dependencies

---

# Checklist for maintainers

## Releases

- Do **NOT** push the green merge button on GitHub.  
Follow the latest version of the [developer/maintainer docs](https://hexatomic.github.io/hexatomic/dev/) for making releases.
- Check that license and citation information for dependencies are complete (each dependency has a folder in `/THIRD-PARTY/`).

2021-11-22 14:38 UTC, sdruskat commented
Hi @clachenmaier, as far as I can see, there is no way to automatically test the update functionality. In a way, this is also outside the scope of testing Hexatomic, as we rely on Eclipse functionality (that should be tested in the Eclipse project itself).

Therefore, I suggest to simply test for the existence of the Update feature (as suggested in a future commit), and test the preferences dialog (which you are already doing), and leave it at that.

What's your opinion on this, @thomaskrause?

---

One other thing to do would be to let the update repository point to `https://hexatomic.github.io/hexatomic/updates/v0/`, which is where we are planning to deploy the update sites to on release.

2021-12-15 14:48 UTC, thomaskrause commented
I merged the develop branch and solved the conflicts which were mostly about versions. The test runs fine the first time, but on second execution the preference test fails

```
Failures: 
  TestHelpMenu.testOpenPreferenceDialog:52 Preference allready set
```

2021-12-16 08:26 UTC, clachenmaier commented
> I merged the develop branch and solved the conflicts which were mostly about versions. 
 Thank you for merging and your review!

> The test runs fine the first time, but on second execution the preference test fails
> Failures: 
>   TestHelpMenu.testOpenPreferenceDialog:52 Preference allready set
 
I tried to fix it. Could you have a look at it again?

Since merging i'm getting some test failures:
`Failures: 
  TestGridEditor.testManualResolveViaF5:1472 expected: <4> but was: <5>
Errors: 
TestGridEditor.testManualResolveViaBodyMenu:1481->openDefaultExample:217->openEditorForDefaultDocument:198 » Timeout,`

Do you observe the same behaviour? I think those aren't even related to the update feature.

2021-12-16 08:53 UTC, sdruskat commented
> Do you observe the same behaviour? I think those aren't even related to the update feature.

You're right, this isn't anything to do with the update feature. It's a timing issue with SWTBot. We need to fix this (not only for this test). Ideally, re-running the action will pass the pipeline, I'll try.

2021-12-16 09:13 UTC, sdruskat commented
@clachenmaier Simply re-running doesn't work, fair enough. I'll try to fix this in a new PR.
In the meantime, I suggest that you try to get rid off the remaining code smells and security hotspots?
Afterwards, we can work together towards better test coverage.

2022-01-04 10:00 UTC, sdruskat requested changes
Hi @clachenmaier, thanks for this PR! Great work!

I've suggested some changes, mostly to change wording and docs. Can I suggest you go through them and commit suggestions/make changes, then `@sdruskat` and `@thomaskrause` us here so we can work on adding some tests to achieve better coverage?

2022-01-05 08:51 UTC, clachenmaier commented on CITATION.cff
> +  version: 3.6.0
@sdruskat I guess it was my mistake. Sorry!! I thought i had to run `mvn cff:create` and `mvn cff:third-party-folder` manually, which was obviously wrong. The project setup is still confusing to me sometimes. Anyways i'll wait for @thomaskrause until i'll commit your suggested changes regarding the citation file.

2022-01-05 08:52 UTC, clachenmaier commented on releng/org.corpus_tools.hexatomic.target/org.corpus_tools.hexatomic.target.tpd
> +	org.eclipse.equinox.p2.metadata.repository
Thank you for clarifying

2022-01-06 08:15 UTC, sdruskat commented on CITATION.cff
> +  version: 3.6.0
Hi @clachenmaier, not sure this is even your fault. Ideally, the Maven CFF plugin should detect duplicates and not add them twice.

2022-03-04 11:10 UTC, sdruskat commented
@sdruskat und @thomaskrause to write tests and review.

2022-03-04 11:11 UTC, sdruskat commented
Document that this module cannot be as thoroughly tested as we'd wish, due to the use of external infrastructure.

2022-03-07 11:11 UTC, thomaskrause commented on CITATION.cff
> +  version: 3.6.0
I investigated the issue and this was caused by a bundled JAR file in pepper-framework for easier inclusion of XMLUnit. This was modelled as some kind of sub-artifact and therefore labelled "pepper-framework" in the Maven dependency  model. I fixed this in 4f750009 by adding a curated template for XMLUnit

2022-03-24 09:52 UTC, thomaskrause commented
I was able to change the launch configuration so it is possible to run the updater from inside Eclipse. This might help debugging a lot. The same option is availabe when running the UI integration tests, but this does not work. Since all references to the update mechanism do mention it is not possible to run the update when started from Eclipse, I doubt there is any easy way to automatically test the update.

I did try to write some unit tests, but the mocking involved is quite extensive and I was not yet able to actually get an automatic test running. While I would still try to invest a limited time to implement automatic logic tests using mocking for, I would also argue to make manual testing as easy as possible. Eclipse itself uses a test matrix (<https://wiki.eclipse.org/Equinox/p2/UI_Manual_Tests>) for manual P2 update tests. I would propose to change the current implementation to

- per default check if there is an available update at startup (no user interaction needed)
- instead of showing a message dialog that there is no update available (which has to be removeed by clicking a button, what is probably something that will make you disable automatic update check), the automatic check at startup should only display a message in the status bar or an error message if there was any failure during the udpate process

This would allow the manual test of "just start Hexatomic" and visual inspection of the status bar to check there is a "no update available" message without any manual interaction like clicking on the update menu. I would check that the maintainer documentation mentions this.
@sdruskat Would you agree this is an acceptable approach, even if this will probably deviate from the "everything is tested automatically" strategy?

2022-04-01 08:40 UTC, sdruskat commented
> @sdruskat Would you agree this is an acceptable approach, even if this will probably deviate from the "everything is tested automatically" strategy?

Yes. I agree with the implementation changes as well. Thanks!

2022-05-16 12:27 UTC, thomaskrause commented
@sdruskat 

I implemented the changes as outlined (message box with question whether to actually apply update, automatic check for updates at startup) and updated the maintainer documentation to include the manual test steps.

2022-05-24 08:38 UTC, sdruskat approved these changes
Nice one, thanks! :taco: 

This generally looks good, I've made some suggestions re wording, etc.

One thing that I noticed:

1. After the auto-restart post-updating, the status bar doesn't say "Hexatomic is up-to-date." I had added a line in the dev docs to that effect, so either this line should be removed again, or replaced by the steps for manual update, or the auto-check after auto-restart should be implemented, so that the status bar reliably shows this message.

2022-05-24 08:38 UTC, sdruskat commented on docs/dev/src/maintenance/contributions/README.md
> +2. Build the product by executing
```suggestion
2. Build the product by executing (from the root of your local source code repository)
```
Make it clearer where this should be run.

2022-05-24 08:38 UTC, sdruskat commented on docs/dev/src/maintenance/contributions/README.md
> +In addition to manually checking the changes of the pull request, you should also check that
```suggestion
In addition to manually checking the changes of the pull request, you should therefore also check that 
```
Minor wording.

2022-05-24 08:38 UTC, sdruskat commented on docs/dev/src/maintenance/contributions/README.md
> +1. Adjust the file `releng/org.corpus_tools.hexatomic.product/p2.inf` and the local update site as repository by adding the following lines (but replace `<SRC>` with the location of your Hexatomic so
```suggestion
1. Adjust the file `releng/org.corpus_tools.hexatomic.product/p2.inf` and the local update site as repository by adding the following lines (but replace `<SRC>` with the location of your Hexatomic source code directory).
```

End sentence properly.

2022-05-24 08:49 UTC, sdruskat approved these changes

2022-05-24 08:49 UTC, sdruskat commented on docs/user/src/update.md
> +If not, a message in the status bar will be displayed, that there is no update available.
```suggestion
If not, a message in the status bar will be displayed, that there is no update available, and that "Hexatomic is up to date".
```
Give the actual status bar line, to avoid confusion.

2022-05-24 08:49 UTC, sdruskat commented on docs/user/src/update.md
> +2. Select *Update*
```suggestion
1. Click on *Help* in the main menu.
2. Select *Update*.
```

Add full stops.

2022-05-24 08:49 UTC, sdruskat commented on docs/user/src/update.md
> +1. If there are updates available, you are asked if you want to install it. Otherwise you will be informed that there are no updates available.
```suggestion
1. If there are updates available, you are asked if you want to install them. Otherwise you will be informed that there are no updates available.
```

Fix typo.

2022-05-24 09:03 UTC, merged